package com.resqnetapp.nearby

interface NearbyConnectionCallbacks {
    fun onPeerFound(peerId: String, peerName: String)
    fun onPeerLost(peerId: String)
    fun onInvitationReceived(peerId: String, peerName: String)
    fun onConnected(peerId: String, peerName: String)
    fun onDisconnected(peerId: String)
    fun onTextReceived(peerId: String, text: String)
    fun onDebugLog(message: String)
    fun onDiscoveryStarted(strategy: String)
    fun onDiscoveryFailed(error: String, strategy: String)
    fun onAdvertisingStarted(deviceId: String, strategy: String)
    fun onAdvertisingFailed(error: String, strategy: String)
    fun onConnectionRequested(endpointId: String, deviceId: String)
    fun onConnectionRequestFailed(endpointId: String, error: String)
    fun onConnectionAccepted(endpointId: String)
    fun onConnectionAcceptFailed(endpointId: String, error: String)
    fun onConnectionRejected(endpointId: String)
    fun onMessageSent(endpointId: String, message: String)
    fun onMessageSendFailed(endpointId: String, error: String)
    fun onFileReceived(endpointId: String, payloadId: Long)
    fun onStreamReceived(endpointId: String, payloadId: Long)
    fun onPayloadTransferUpdate(endpointId: String, payloadId: String, status: String, bytesTransferred: Long, totalBytes: Long)
    fun onConnectionEstablished(endpointId: String, status: String, statusCode: Int)
    fun onConnectionFailed(endpointId: String, status: String, statusCode: Int)
    fun onDeviceInfo(manufacturer: String, model: String, brand: String, device: String, sdkVersion: Int, release: String, hasBluetoothLe: Boolean, hasWifiDirect: Boolean, deviceId: String, serviceId: String)
    fun onDeviceReadiness(hasAllPermissions: Boolean, missingPermissions: List<String>, isBluetoothEnabled: Boolean, isLocationEnabled: Boolean, isWifiEnabled: Boolean, bluetoothSupported: Boolean, deviceInfo: Map<String, Any>)
    fun onPermissionRequestFailed(error: String)
    fun onBluetoothEnableResult(enabled: Boolean)
    fun onBluetoothEnableFailed(error: String)
    fun onLocationEnableFailed(error: String)
    fun onWifiEnableResult(enabled: Boolean)
    fun onDiagnosticComplete(results: List<Map<String, Any>>)
    fun onCompatibilityModeEnabled(mode: String)
}